### ISSUE TITLE
Interesting Tool for this

### ISSUE THREAD

**Issue by timsehn** [mhagiwara/github-typo-corpus#1]
This is very cool.

We have a tool called Dolt (https://www.dolthub.com) that puts Git semantics around a SQL database. Would you consider working with us to version the output of your scraper. We are happy to run it for you in our Airflow instance.

https://github.com/liquidata-inc/liquidata-etl-jobs

**Comment by mhagiwara** [comment]
Um, maybe. You are free to version our dataset on your platform, but I don't think either of us has enough time or motivation to do that ourselves.

**Comment by mhagiwara** [comment]
CC: @mamita1092

**Comment by timsehn** [comment]
Cool. We'll do it :-)
