### ISSUE TITLE
SyntaxError: invalid syntax running collect_repositories.py

### ISSUE THREAD

**Issue by MNCTTY** [mhagiwara/github-typo-corpus#2]
Hi! I tried to download your dataset and faced this issue while running `python3 collect_repositories.py`

```
github-typo-corpus/src$ python3 collect_repositories.py 
  File "collect_repositories.py", line 55
    archive_url = f'https://data.gharchive.org/{date_str}-{hour}.json.gz'
```
Can you help, please? May be I do something wrong, but I didn't see instructions in readme

**Comment by mhagiwara** [comment]
Which Python 3 are you using? The f-string used here needs Python 3.6+

**Comment by mhagiwara** [comment]
Also, you don't need to run the script in order to download the dataset (unless you are interested in downloading all the repositories all over again)—it's already there! See README.
