### ISSUE TITLE
Dataset Clarifications

### ISSUE THREAD

**Issue by TrigonaMinima** [mhagiwara/github-typo-corpus#3]
Hi,
I had a few questions regarding the dataset and the methodology:

1. Why are cases where there a space between non letter characters is considered as a typo? I am talking about the cases like this:

```
{
   "repo":"https://github.com/abacritt/angularx-social-login",
   "commit":"d4c912f5ccd70c81f424fadbf1fe1a2ecb942f07",
   "message":"Fix typo\n",
   "edits":[
      {
         "src":{
            "text":"            IN.User.authorize(function(){",
            "path":"src/lib/src/providers/linkedIn-login-provider.ts",
            "lang":"eng",
            "ppl":14.759690820409018
         },
         "tgt":{
            "text":"            IN.User.authorize(function() {",
            "path":"src/lib/src/providers/linkedIn-login-provider.ts",
            "lang":"eng",
            "ppl":13.02657495778316
         },
         "prob_typo":0.9393920322691369,
         "is_typo":true
      },
      {
         "src":{
            "text":"            IN.User.logout(function(){",
            "path":"src/lib/src/providers/linkedIn-login-provider.ts",
            "lang":"eng",
            "ppl":21.30207029147685
         },
         "tgt":{
            "text":"            IN.User.logout(function() {",
            "path":"src/lib/src/providers/linkedIn-login-provider.ts",
            "lang":"eng",
            "ppl":18.466537526108358
         },
         "prob_typo":0.9433146599837509,
         "is_typo":true
      }
   ]
}
```
Here there is only a space between `)` and `{`. Doesn't it come under semantic error? Also isn't this type for programming language as opposed to human languages?

2. I checked for `"lang":"hin"` in the dataset and found *many* cases similar to the one I have listed down. There is no Hindi character in the message due to which it might have been tagged as Hindi. What could be the reason behind this? The language identifier might have these irregularities. Also coincidentally, this kind of error also shows another example for the 1st point I mentioned. Does having these examples help?

```
{
   "repo":"https://github.com/apache/airflow",
   "commit":"b81bd08a334efa5242af705743519be43346295e",
   "message":"[AIRFLOW-2538] Update faq doc on how to reduce airflow scheduler latency\n\nMake sure you have checked",
   "edits":[
      {
         "src":{
            "text":"---------------------------------------------------------------------------------------------",
            "path":"docs/faq.rst",
            "lang":"hin"
         },
         "tgt":{
            "text":"-----------------------------------------------------------------------------------------",
            "path":"docs/faq.rst",
            "lang":"hin"
         }
      }
   ]
}
```

3. In the above example, there is not `is_typo` flag. This I also observed in cases for the other languages as well. What might be the reason for that?

I am trying to understand the whole methodology and not undermining your work. I read the paper as well. It was very well written; classifier was especially neat. Thanks for releasing the dataset.

**Comment by mhagiwara** [comment]
Please read the paper https://arxiv.org/abs/1911.12893 first and let me know if you still have questions

**Comment by TrigonaMinima** [comment]
I did read the paper before asking the questions. I understand that 4 types of errors are found, out of which, 3 were classed under typos (mechanical, spell, grammaticak). But the examples I listed confused me a bit. Please let me know if you need more clarification regarding the points I raised.

**Comment by mhagiwara** [comment]
Changes in spaces and punctuation are classified into `mechanical` errors, which are, according to our definition, typos. Regarding 2, it's probably a classification error made by the language detector we used (https://github.com/mhagiwara/nanigonet), so submitting an issue there might help. Re: 3, as written in README, we only provide those fields for the top 3 languages (eng, jpn, cmn-hans).

**Comment by TrigonaMinima** [comment]
Thanks for the clarifications. Submitted the miss-classification issue on the https://github.com/mhagiwara/nanigonet repo (https://github.com/mhagiwara/nanigonet/issues/2).
